apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- namespace.yaml
- gotk-crds.yaml
- gotk-components.yaml
- gotk-sync.yaml
- limit-range.yaml
- resource-quota.yaml
- rbac.yaml
images:
- name: ghcr.io/fluxcd/source-controller
  newName: acrakshj4l26oiftkuy.azurecr.io/live/fluxcd/source-controller
- name: ghcr.io/fluxcd/kustomize-controller
  newName: acrakshj4l26oiftkuy.azurecr.io/live/fluxcd/kustomize-controller
