apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: a0005-i
resources:
- networkpolicy.yaml
- deployment.yaml
- allowed-traffic.yaml
images:
- name: YOUR_ACR.azurecr.io/live/a0005/chain-api
  newName: acrakshj4l26oiftkuy.azurecr.io/live/a0005/chain-api